/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewComponents;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.List;

/**
 *
 * @author Paulo.Tenorio
 */
public class Test extends javax.swing.JPanel {
    private Color cor[][];
    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    public void setCor(Color[][] cor) {
        this.cor = cor;
    }
    
    
    
    @Override
    public void paint(java.awt.Graphics g)
    {
        super.paint(g);
        BufferedImage img = new BufferedImage(this.getSize().width,this.getSize().height,BufferedImage.TYPE_INT_ARGB);
        if (cor!=null)
        {
            for (int i=0;i<cor.length;i++)
            {
                if (cor[0]!=null)
                {
                    for (int j=0;j<cor[0].length;j++)
                    {
                        if (cor[i][j]!=null)
                        img.setRGB(i, j, cor[i][j].getRGB());
                        else
                        {
                            System.out.println("erro em = " + i + "," + j);
                        }
                    }
                }

            }
        }
        g.drawImage(img,0,0,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
